### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ZeliTheZealot** [valentjn/languagetool-languageserver#303]
**Describe the bug**
StringIndexOutOfBoundsException

**Steps to reproduce**
Run the command
`(base) computer_name:~ username$ ltex-ls-16.0.0/bin/ltex-cli "filename.tex"`

**Expected behavior**
Not sure. It is my first time running it.

**Sample document**
It is very long and confidential unfortunately. I can say that it is based on [this template](https://www.overleaf.com/latex/templates/software-engineer-resume/gqxmqsvsbdjf).

<details>

```
REPLACE_THIS_WITH_SAMPLE_DOCUMENT
```

</details>

**LTeX configuration**
No configuration.

<details>

```
REPLACE_THIS_WITH_LTEX_CONFIGURATION
```

</details>

**LTeX LS log**
See below

<details>

```
filename.tex:51:28: info: Possible typo: you repeated a whitespace [WHITESPACE_RULE]
java.lang.StringIndexOutOfBoundsException: begin 27, end 165, length 37
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.bsplines.lspcli.client.Checker$Companion.printDiagnostic(Checker.kt:185)
	at org.bsplines.lspcli.client.Checker$Companion.access$printDiagnostic(Checker.kt:135)
	at org.bsplines.lspcli.client.Checker.checkFile(Checker.kt:129)
	at org.bsplines.lspcli.client.Checker.check(Checker.kt:66)
	at org.bsplines.lspcli.client.Checker.check(Checker.kt:39)
	at org.bsplines.lspcli.LspCliLauncher.call(LspCliLauncher.kt:174)
	at org.bsplines.lspcli.LspCliLauncher$Companion.main(LspCliLauncher.kt:212)
	at org.bsplines.lspcli.LspCliLauncher.main(LspCliLauncher.kt)
```

</details>

**Version information**

- Operating system:  macOS 13.6.3
- ltex-ls: 16.0.0
- Java: 1.8.0_401

**Additional context/information**
Nothing at the moment.

**Comment by kmccurley** [comment]
I'm finding ltex-ls to be unusable because it throws an exception on over half of the inputs that I've tried it on (my inputs are from the pipeline of a journal and supplied by the authors). I'm only using it from the command line on Ubuntu 22.04.4. A sample stack trace is:
```
java.lang.StringIndexOutOfBoundsException: begin 24, end 26, length 25
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.bsplines.lspcli.client.Checker$Companion.printDiagnostic(Checker.kt:185)
	at org.bsplines.lspcli.client.Checker$Companion.access$printDiagnostic(Checker.kt:135)
	at org.bsplines.lspcli.client.Checker.checkFile(Checker.kt:129)
	at org.bsplines.lspcli.client.Checker.check(Checker.kt:66)
	at org.bsplines.lspcli.client.Checker.checkDirectory(Checker.kt:75)
	at org.bsplines.lspcli.client.Checker.check(Checker.kt:60)
	at org.bsplines.lspcli.client.Checker.check(Checker.kt:39)
	at org.bsplines.lspcli.LspCliLauncher.call(LspCliLauncher.kt:174)
	at org.bsplines.lspcli.LspCliLauncher$Companion.main(LspCliLauncher.kt:212)
	at org.bsplines.lspcli.LspCliLauncher.main(LspCliLauncher.kt)
Jun 16, 2024 11:49:59 AM org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor run
SEVERE: java.io.IOException: Stream closed
```
